<<kops
Landmark Technologies 
Tel: +1 437 215 2483 
mylandmarktech@gailcom 
www.mylandmarktech.com 
kops
Setup Kubernetes (K8s) Cluster on AWS Using KOPS

#!/bin/bash
=#1) Create Ubuntu EC2 instance in AWS and create kops user
   sudo adduser kops
   sudo echo "kops  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/kops
   sudo su - kops

=#2) install AWSCLI

 sudo apt update -y
 sudo apt install unzip wget -y
 sudo curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
 sudo apt install unzip python -y
 sudo unzip awscli-bundle.zip
 sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
 
 
=#3) Install kops software on ubuntu instance:

 	#Install wget if not installed
 	sudo apt install wget -y
 	sudo wget https://github.com/kubernetes/kops/releases/download/v1.18.2/kops-linux-amd64
 	sudo chmod +x kops-linux-amd64
 	sudo mv kops-linux-amd64 /usr/local/bin/kops
 
=#4) Install kubectl = command line utility for kubernetes

 sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
 sudo chmod +x ./kubectl
 sudo mv ./kubectl /usr/local/bin/kubectl
 
 
 
 aws s3 mb s3:/class24.local
 # 
 aws s3 ls

=# 5) Create an IAM role from AWS Console or CLI with below Policies.

	AmazonEC2FullAccess  = ecs instances
	AmazonS3FullAccess   = key-value-store 
	IAMFullAccess        = 
	AmazonVPCFullAccess  = vpc 
    user cannot manage billing 


Then Attach IAM role to ubuntu server from Console Select KOPS Server --> Actions --> 
    Instance Settings/Security --> Attach/Replace IAM Role --> Select the role which
You Created. --> Save.
   


#6) create an S3 bucket Execute below commond in KOPS Server use unique bucket name if you get bucket name exists error.

  
	aws s3 mb s3://class24b.local
	aws s3 ls
	
    ex:
	S3 bucket name should be unique across AWS accounts 
	aws s3 mb s3://simonlegah.k8s.local    s3://nubong.k8s.local
     
	Expose environment variable:

    # Add env variables in bashrc
    vi .bashrc
	
	# Give Unique Name And S3 Bucket which you created.
	export NAME=class24.k8s.local
	export KOPS_STATE_STORE=s3://class24b.local
 
    source .bashrc
	
=#7) Create sshkeys before creating cluster

    ssh-keygen
 

=# 8)Create kubernetes cluster definitions on S3 bucket

kops create cluster --zones us-west-1c --networking weave --master-size t2.medium --master-count 1 --node-size t2.medium --node-count=2 ${NAME}
	
	kops create cluster --zones us-east-2a, \
  zones us-east-2c --networking weave --master-size t2.medium \
  --master-count 2 --node-size t2.medium --node-count=2 ${NAME}

	kops create secret --name ${NAME} sshpublickey admin -i ~/.ssh/id_rsa.pub

# 9) Create kubernetes cluser

	 kops update cluster ${NAME} --yes

# 10) Validate your cluster(KOPS will take some time to create cluster ,Execute below commond after 3 or 4 mins)

	   kops validate cluster
 
# 11) To list nodes

	  kubectl get nodes 
  
  
  
# 12) To Delete Cluster

   kops delete cluster --name=${NAME} --state=${KOPS_STATE_STORE} --yes  
   
====================================================================================================


13# IF you wan to SSH to Kubernates Master or Nodes Created by KOPS. You can SSH From KOPS_Server

ssh  admin@<IPOrDNS>
it above command  is not working
then execute
ssh -i ~/.ssh/id_rsa admin@<IPOrDNS>
Suggestions:
 * validate cluster: kops validate cluster --wait 10m
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa ubuntu@api.class24.k8s.local
 * the ubuntu user is specific to Ubuntu. If not using Ubuntu please use the appropriate user based on your OS.
 * read about installing addons at: https://kops.sigs.k8s.io/operations/addons.

 
Suggestions:
 * validate cluster: kops validate cluster --wait 10m
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.class22.k8s.local
 * the ubuntu user is specific to Ubuntu. If not using Ubuntu please use the appropriate user based on your OS.
 * read about installing addons at: https://kops.sigs.k8s.io/operations/addons.

ssh -i "~/.ssh/id_rsa" ubuntu@ec2-54-219-178-194.us-west-1.compute.amazonaws.com

***************************************************************

A new kops version is available: 1.18.2

Upgrading is recommended
More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_kops.md#1.18.2

sudo wget https://github.com/kubernetes/kops/releases/download/v1.18.2/kops-linux-amd64

sudo echo "eksadmin  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/eksadmin

sudo echo "kops  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/kops
  



apps.landmarkteck.net  --> 
app.com--> query Global DNS
     ---> aced4ce254c6c4c67b9929efb7629a01-1489509669.us-west-1.elb.amazonaws.com
                  ---> Nodes
                         ---> pod

apps.landmarkteck.net/
    apps.landmarkteck.net/webapp
    apps.landmarkteck.net/javaapp

****  
   //
****
